// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5jMf2ZY89J56hycDocwTf5E7PUZRXs0E',
    appId: '1:144451514722:web:6ce888371d4e20ec107c3b',
    messagingSenderId: '144451514722',
    projectId: 'ellemoraassignment',
    authDomain: 'ellemoraassignment.firebaseapp.com',
    databaseURL: 'https://ellemoraassignment-default-rtdb.firebaseio.com',
    storageBucket: 'ellemoraassignment.firebasestorage.app',
    measurementId: 'G-4ST8NF1MD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhKp8wAc0CPj55sesxbsHkMybAm8vGndo',
    appId: '1:144451514722:android:ba998a4e644bcaa3107c3b',
    messagingSenderId: '144451514722',
    projectId: 'ellemoraassignment',
    databaseURL: 'https://ellemoraassignment-default-rtdb.firebaseio.com',
    storageBucket: 'ellemoraassignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmD65UOvsMFfD6CfAUdWqWF7H5pAX1R24',
    appId: '1:144451514722:ios:d209b5826e434e94107c3b',
    messagingSenderId: '144451514722',
    projectId: 'ellemoraassignment',
    databaseURL: 'https://ellemoraassignment-default-rtdb.firebaseio.com',
    storageBucket: 'ellemoraassignment.firebasestorage.app',
    iosBundleId: 'com.example.rashiTechologies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmD65UOvsMFfD6CfAUdWqWF7H5pAX1R24',
    appId: '1:144451514722:ios:d209b5826e434e94107c3b',
    messagingSenderId: '144451514722',
    projectId: 'ellemoraassignment',
    databaseURL: 'https://ellemoraassignment-default-rtdb.firebaseio.com',
    storageBucket: 'ellemoraassignment.firebasestorage.app',
    iosBundleId: 'com.example.rashiTechologies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5jMf2ZY89J56hycDocwTf5E7PUZRXs0E',
    appId: '1:144451514722:web:ec065e5b396620a7107c3b',
    messagingSenderId: '144451514722',
    projectId: 'ellemoraassignment',
    authDomain: 'ellemoraassignment.firebaseapp.com',
    databaseURL: 'https://ellemoraassignment-default-rtdb.firebaseio.com',
    storageBucket: 'ellemoraassignment.firebasestorage.app',
    measurementId: 'G-BVLHRY4805',
  );
}
